version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      MOTD: "Bem-Vindos a Alta Cúpula do Partido dos Trabalhadores!"
      ICON: "https://ibb.co/b5xXQzFz"
      OVERRIDE_ICON: "true"
      ONLINE_MODE: "false"
      USE_AIKAR_FLAGS: "true"
      TZ: "America/Sao_Paulo"
      TYPE: "PAPER"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: "25575"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-5.3.3-SNAPSHOT.jar
    volumes:
      - ./data:/data
    networks:
      - mc-net
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    restart: unless-stopped

  mc-backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "8h"
      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
      PRUNE_BACKUPS_DAYS: 7
      INITIAL_DELAY: 2m
      COMPRESS_BACKUPS: "true"
      COMPRESSION_METHOD: "zstd"
      POST_BACKUP_SCRIPT: "/scripts/discord-alert.sh"
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
      - ./scripts:/scripts:ro
    networks:
      - mc-net
    restart: unless-stopped

networks:
  mc-net: